steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', '${_ARTIFACT_REGISTRY}/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}', '.' , '--build-arg', 'REACT_APP_LOGIN_LINK=${_REACT_APP_LOGIN_LINK}' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', '${_ARTIFACT_REGISTRY}/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', '${_SERVICE_NAME}', '--platform', 'managed', '--region', '${_REGION}', '--image', '${_ARTIFACT_REGISTRY}/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}']
  
images:
- '${_ARTIFACT_REGISTRY}/$PROJECT_ID/${_REPOSITORY}/${_IMAGE_NAME}'
